version: '3.1'
services:
    auth_service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: auth_service
        restart: unless-stopped
        env_file: .env
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - auth_mongodb
        links:
            - "auth_mongodb"
        networks:
            - backend

    auth_mongodb:
        image: mongo:4.0.3
        container_name: auth_mongodb
        restart: unless-stopped
        volumes:
            - "/tmp/mongo-auth-entrypoint/:/docker-entrypoint-initdb.d/"
        ports:
            - "27017:27017"
        expose:
            - "27017"
        networks:
            - backend

networks:
  backend:
    

    
    

  